import type { Metadata } from "next";
import "./globals.css";
import { inter, titleFont } from "@/config/fonts";
import { TopMenu } from "@/components";

export const metadata: Metadata = {
  title: "Teslo | Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${titleFont.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
