import type { Metadata } from "next";
import "./globals.css";
import { inter, titleFont } from "@/config/fonts";
import { Sidebar, TopMenu } from "@/components";

export const metadata: Metadata = {
  title: "Teslo | Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${titleFont.variable} antialiased`}
        style={{ overflowX: 'hidden' }}
        suppressHydrationWarning
      >
        <main className="min-h-screen">
              <TopMenu />
              <Sidebar />
        
              <div className="container mx-auto max-w-7xl px-4">
               {children}
              </div>
              </main>
      </body>
    </html>
  );
}
